# Generated by Django 5.0.1 on 2024-01-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='size_l',
            field=models.BooleanField(default=False, verbose_name='Size L'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_m',
            field=models.BooleanField(default=False, verbose_name='Size M'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_s',
            field=models.BooleanField(default=False, verbose_name='Size S'),
        ),
    ]
