# Generated by Django 5.0.4 on 2024-04-18 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
