# Generated by Django 5.0.4 on 2024-04-18 07:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_product_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='featured_products_images/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2024, 4, 25, 10, 1, 25, 666))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.color')),
            ],
        ),
    ]
