# Generated by Django 5.0.4 on 2024-04-18 07:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_featuredproduct_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 10, 14, 30, 947305)),
        ),
    ]
