# Generated by Django 5.0.4 on 2024-04-26 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_remove_featuredproduct_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 18, 42, 57, 278730)),
        ),
    ]
