# Generated by Django 5.0.4 on 2024-04-26 16:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_product_is_recommend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 19, 0, 9, 39275)),
        ),
        migrations.CreateModel(
            name='UniqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='unique_products_images/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2024, 5, 3, 19, 0, 9, 39275))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.color')),
            ],
        ),
    ]
