# Generated by Django 5.0.4 on 2024-05-02 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_featuredproduct_release_date_uniqueproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 11, 48, 19, 894350)),
        ),
        migrations.AlterField(
            model_name='uniqueproduct',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 11, 48, 19, 895349)),
        ),
    ]
