# Generated by Django 5.0.4 on 2024-05-02 08:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_featuredproduct_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 11, 50, 14, 747277)),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uniqueproduct',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 11, 50, 14, 747277)),
        ),
    ]
